language: node_js
node_js:
  - "4.1"

before_script:
  - rvm install ruby 2.3.0
  - rvm use 2.3.0
  - ruby -v
  - gem install jekyll
  - gem update --system

install:
  - npm install

script:
  - npm run deploy

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

branches:
  only:
    - master
